# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43542eb5afc5d48a2418f6a98b481c533e060be00f10c00eb42646a7f38412d70d403e2300f1ed6fab488ad87e2d2aa9def5aec2dd49cd42a839454322e9ff82

test:
  secret_key_base: dc24a5b3cd9eacd68c2cd20c0f1b59255d9dc32b41ccf69bc6613c5ddbd686b96280f275b1db3839eb81bfd1adc6adbef1785501bda3d1c9114a1d1090a08b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
